name: Expo APK Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-apk:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed')
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.0

      # Install and Setup EAS
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_ACCESS_TOKEN }}

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Build the Android APK
      - name: Build Android APK
        run: eas build --platform android --profile groceries --non-interactive

  download-apk:
    name: Download Expo APK
    needs: build-apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install expo-cli
        run: npm install -g expo-cli

      - name: Download Expo APK
        run: |
          CI=1 npx expo fetch:android:apk
          mkdir -p ./apks
          mv *.apk ./apks/
