name: Expo APK Build

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.0

      # Install and Setup EAS
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_ACCESS_TOKEN }}

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Build the Android APK
      - name: Build Android APK
        run: eas build --platform android --profile groceries --non-interactive

  download-apk:
    name: Download Expo APK
    needs: build-apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install expo-cli
        run: npm install -g eas-cli

      - name: Download Expo APK
        run: |
          BUILD_ID=$(eas build:list --platform android --status finished --json | jq -r '.[0].id')
          ARTIFACT_LINK=$(eas build:show --platform android --build-id $BUILD_ID --json | jq -r '.artifacts[0].url')
          curl -L -o ./apk/app.apk $ARTIFACT_LINK
