name: Expo APK Build

on:
  push:
    branches:
      - main # Trigger builds on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.13.0

      # Install EAS CLI globally
      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_ACCESS_TOKEN }}

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Build the Android APK
      - name: Build Android APK
        run: eas build --platform android --profile release --non-interactive

      # Upload the APK file
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: groceries-release-apk
          path: ./app/build/outputs/apk/release/app-release.apk
